# SPDX-FileCopyrightText: 2026 numlike contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "numlike"
version = "0.1.1"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Numeric traits for generic mathematics. Less restrictive alternative to num-traits."
repository = "https://github.com/mikwielgus/numlike"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["mathematics", "numerics", "no_std"]
categories = ["algorithms", "science", "no-std"]
edition = "2024"

[features]
default = ["std"]
## Disable for `no_std` compatibility. Required for power, fused multiply-add,
## and Euclidean division on floats.
std = []

[dependencies]
document-features = { version = "0.2", optional = true }
