# SPDX-FileCopyrightText: 2026 numlike contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "numlike"
version = "0.1.3"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Numeric traits for generic mathematics. Less restrictive alternative to num-traits."
repository = "https://github.com/mikwielgus/numlike"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["mathematics", "numerics", "no_std"]
categories = ["algorithms", "science", "no-std"]
edition = "2024"

[features]
default = ["std"]

## Disable for `no_std` compatibility.
std = []

## Use `libm` to implement some operations if `std` is disabled.
libm = ["dep:libm"]

[dependencies]
document-features = { version = "0.2", optional = true }
libm = { version = "0.2", optional = true }

# Enable all feature flags for docs.rs and use scraped examples.
[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
